### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by crazy4groovy** [IonicaBizau/image-to-ascii-cli#11]
```
D:\>image-to-ascii -i bg.jpg
error spawn gm ENOENT
```

Windows 7
nodejs v6.10.2

**Comment by nickfogle** [comment]
@crazy4groovy you probably need to install `graphicsmagick`

**Comment by IonicaBizau** [comment]
Like @nickfogle mentioned, the easiest way on Windows would be to install GraphicsMagick.
