### ISSUE TITLE
Deprecation Warning: os.tmpDir()

### ISSUE THREAD

**Issue by haysclark** [IonicaBizau/image-to-ascii-cli#8]
(node:39821) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by IonicaBizau** [comment]
Thanks for that! Will take care of it soon. :+1:

**Comment by Krato** [comment]
Some news?

**Comment by IonicaBizau** [comment]
I'm on it, thanks for pinging!

**Comment by IonicaBizau** [comment]
This is my view: https://twitter.com/IonicaBizau/status/908336079245324288 😁
